# Generated by Django 4.1.7 on 2023-03-12 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="author",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ad",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="ad",
            name="description",
            field=models.CharField(default="dsf", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ad",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="django_media"),
        ),
        migrations.AddField(
            model_name="ad",
            name="price",
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ad",
            name="title",
            field=models.CharField(default="sadafa", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="ad",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="ads.ad"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="text",
            field=models.CharField(default="sdfsadfafasgas", max_length=200),
            preserve_default=False,
        ),
    ]
