# Generated by Django 4.1.7 on 2023-03-12 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.CharField(
                default=datetime.datetime(2023, 3, 12, 15, 46, 24, 236943),
                max_length=100,
            ),
        ),
    ]
