# Generated by Django 4.1.7 on 2023-03-12 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.CharField(
                default=datetime.datetime(2023, 3, 12, 16, 20, 4, 550085),
                max_length=100,
            ),
        ),
    ]
