# Generated by Django 4.1.7 on 2023-03-13 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.CharField(
                default=datetime.datetime(2023, 3, 13, 6, 27, 44, 231200),
                max_length=100,
            ),
        ),
    ]
