# Generated by Django 4.1.7 on 2023-03-14 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_image_alter_user_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.CharField(
                default=datetime.datetime(2023, 3, 14, 23, 20, 6, 255902),
                max_length=100,
            ),
        ),
    ]
